export const products = [
    {
      id: "hpomen16-xf0016nb",
      name: "HP Omen 16-xf0016nb",
      oldPrice: "€1799.00",
      newPrice: "€1249.00",
      image: "https://image.coolblue.be/max/500x500/products/1941017",
      star1: "/star.svg",
      star2: "/star.svg",
      star3: "/star.svg",
      star4: "/star.svg",
      star5: "/star_half.svg",
      reviewsCount: 4,
      category: "Gaming",
      laptopOrDesktop : "Laptops",
      en: {
        description: "Eng desc"
      },
      ned: {
        description: "ned desc"
      },
      storageOptions: ["512GB", "1TB", "2TB", "4TB"],
      memoryOptions: ["16GB", "32GB", "64GB"],
      processorOptions: ["Core Ultra 7 155H", "Core Ultra 7 165H", "Core Ultra 9 185H",],
      gpuOptions: ["Intel Arc", "RTX 4050", "RTX 4060", "RTX 4070"]
    },
    {
      id: "Dell-XPS-16-Intel",
      name: "Dell XPS 16-inch Intel",
      oldPrice: "€3499.00",
      newPrice: "€3199.00",
      image: "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/16-9640/media-gallery/silver/touch/notebook-laptop-xps-16-9640-t-silver-gallery-2.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=612&qlt=100,1&resMode=sharp2&size=612,402&chrss=full",
      smImg1: "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/16-9640/media-gallery/silver/touch/notebook-laptop-xps-16-9640-t-silver-gallery-4.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=662&qlt=100,1&resMode=sharp2&size=662,402&chrss=full",
      smImg2: "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/16-9640/media-gallery/silver/touch/notebook-laptop-xps-16-9640-t-silver-gallery-7.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=624&qlt=100,1&resMode=sharp2&size=624,402&chrss=full",
      smImg3: "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/16-9640/media-gallery/silver/touch/notebook-laptop-xps-16-9640-t-silver-gallery-10.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=582&qlt=100,1&resMode=sharp2&size=582,402&chrss=full",
      star1: "/star.svg",
      star2: "/star.svg",
      star3: "/star.svg",
      star4: "/star.svg",
      star5: "/star_half.svg",
      reviewsCount: 5,
      category: "Notebook",
      laptopOrDesktop : "Laptops",
      en: {
        description: "Bring your most intensive projects to life with our most powerful XPS laptop[1], powered by Intel® Core™ Ultra processors with integrated AI, all wrapped in an iconic design.",
        inStockOrOutOfStock: "In Stock",
      },
      ned: {
        description: "Breng uw meest intensieve projecten tot leven met onze krachtigste XPS laptop[1], aangedreven door Intel® Core™ Ultra processors met geïntegreerde AI, allemaal verpakt in een iconisch ontwerp.",
        inStockOrOutOfStock: "Op Voorraad",
      },
      storageOptions: ["512GB", "1TB", "2TB", "4TB"],
      memoryOptions: ["16GB", "32GB", "64GB"],
      processorOptions: ["Core Ultra 7 155H", "Core Ultra 7 165H", "Core Ultra 9 185H"],
      gpuOptions: ["Intel Arc", "RTX 4050", "RTX 4060", "RTX 4070"],
      inStockOrOutOfStockClassName: "instock"
    },
    {
      id: "Macbook-M2-(2022)-Air-13-inch",
      name: "Macbook M2 (2022) Air 13-inch",
      oldPrice: "€1399.00",
      newPrice: "€1249.00",
      image: "https://image.coolblue.be/max/500x500/products/1766893",
      star1: "/star.svg",
      star2: "/star.svg",
      star3: "/star.svg",
      star4: "/star.svg",
      star5: "/star.svg",
      reviewsCount: 8,
      category: "Notebook",
      laptopOrDesktop : "Laptops",
    },
    {
      id: "Asus-ROG-Zephyrus-G14",
      name: "Asus ROG Zephyrus G14",
      oldPrice: "€1799.00",
      newPrice: "€1499.00",
      image: "https://image.coolblue.be/max/500x500/products/2057465",
      star1: "/star.svg",
      star2: "/star.svg",
      star3: "/star.svg",
      star4: "/star.svg",
      star5: "/star_empty.svg",
      reviewsCount: 2,
      category: "Gaming",
      laptopOrDesktop : "Laptops",
    },
    {
      id: "Lenovo-ThinkPad-X1-Carbon-Gen-11",
      name: "Lenovo ThinkPad X1 Carbon Gen 11",
      oldPrice: "€1649.00",
      newPrice: "€1549.00",
      image: "https://image.coolblue.be/max/500x500/products/2060721",
      star1: "/star.svg",
      star2: "/star.svg",
      star3: "/star.svg",
      star4: "/star.svg",
      star5: "/star_half.svg",
      reviewsCount: 7,
      category: "Notebook",
      laptopOrDesktop : "Laptops",
    },
    {
      id: "Acer-Predator-Helios-Neo-16",
      name: "Acer Predator Helios Neo 16",
      oldPrice: "€1499.00",
      newPrice: "€1399.00",
      image: "https://image.coolblue.be/max/500x500/products/1947419",
      star1: "/star.svg",
      star2: "/star.svg",
      star3: "/star.svg",
      star4: "/star.svg",
      star5: "/star_half.svg",
      reviewsCount: 2,
      category: "Gaming",
      laptopOrDesktop : "Laptops",
    },
    {
      id: 7,
      name: "Microsoft Surface Laptop 5",
      oldPrice: 1599,
      newPrice: 1399,
      stars: 4.5,
      reviewsCount: 15
    },
    {
      id: 8,
      name: "Razer Blade 15",
      oldPrice: 1899,
      newPrice: 1699,
      stars: 5,
      reviewsCount: 12
    },
    {
      id: 9,
      name: "HP Spectre x360 14",
      oldPrice: 1599,
      newPrice: 1399,
      stars: 4.5,
      reviewsCount: 21
    },
    {
      id: 10,
      name: "Samsung Galaxy Book Pro 360",
      oldPrice: 1399,
      newPrice: 1199,
      stars: 4,
      reviewsCount: 17
    },
    {
      id: 11,
      name: "Gigabyte Aero 15",
      oldPrice: 1799,
      newPrice: 1599,
      stars: 4.5,
      reviewsCount: 14
    },
    {
      id: 12,
      name: "MSI GS66 Stealth",
      oldPrice: 1699,
      newPrice: 1499,
      stars: 5,
      reviewsCount: 19
    }
  ];
  